name: apklis_direct_payment_checker_example
description: Demuestra cómo utilizar el paquete apklis_direct_payment_checker.

publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  apklis_direct_payment_checker:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

flutter:
  uses-material-design: true
